---
title: "CPS_Simulation_analysis"
author: "Genevieve Sullivan"
date: "2/28/2020"
output: html_document
---
```{r}
Final = read.csv("/Users/genevievesullivan/Desktop/CPS 2019 Project/Sensitivity_Simulation_analysis/Fruit_EnABLe_031720 sensitivity_prevalence-table.csv",skip=6)
Final = read.csv("/Users/genevievesullivan/Desktop/CPS 2019 Project/Sensitivity_Simulation_analysis/Fruit_EnABLe_B_030120 validation_simulation_sensitivity-table (1).csv", skip=6)

#z1 = as.numeric(as.character(Final$z1.prev))
#z2 = as.numeric(as.character(Final$z2.prev))
#z3 = as.numeric(as.character(Final$z3.prev))
#zones = cbind.data.frame(z1,z2,z3)

Final$w.zones.pre = Final$w.zones.pre
Final$w.zones.beg = Final$w.zones.beg
Final$w.zones.mid = Final$w.zones.mid
Final$w.zones.post = Final$w.zones.post

```


```{r}
#######LS dynamics on surfaces in different zones - prevalence

#install.packages("vioplot")
library(vioplot)

plot(1,1,xlim=c(0,5),ylim=c(0,50),type="n",
     xlab="",ylab="Prevalence (%)",axes=FALSE)
## bottom axis, with user-specified labels
axis(side=1,at=1:4,labels=c("pre-op","beginning","middle","end"))
axis(side=2)
vioplot(Final$w.zones.pre,at=1,col="lightgrey",add=TRUE)
vioplot(Final$w.zones.beg,at=2,col="lightgrey",add=TRUE)
vioplot(Final$w.zones.mid,at=3,col="lightgrey",add=TRUE)
vioplot(Final$w.zones.post,at=4,col="lightgrey",add=TRUE)
title("Wednesday")
```


```{r}
plot(1,1,xlim=c(0,4),ylim=c(0,65),type="n",
     xlab="",ylab="Prevalence (%)",axes=FALSE)
## bottom axis, with user-specified labels
axis(side=1,at=1:3,labels=c("Monday","Wednesday","Friday"))
axis(side=2)
vioplot(Final$m.zones.beg,at=1,col="lightgrey",add=TRUE)
vioplot(Final$w.zones.beg,at=2,col="lightgrey",add=TRUE)
vioplot(Final$f.zones.beg,at=3,col="lightgrey",add=TRUE)
title("Beginning of Day")
```


```{r}
plot(1,1,xlim=c(0,4),ylim=c(0,65),type="n",
     xlab="",ylab="Prevalence (%)",axes=FALSE)
## bottom axis, with user-specified labels
axis(side=1,at=1:3,labels=c("Monday","Wednesday","Friday"))
axis(side=2)
vioplot(Final$m.zones.post,at=1,col="lightgrey",add=TRUE)
vioplot(Final$w.zones.post,at=2,col="lightgrey",add=TRUE)
vioplot(Final$f.zones.post,at=3,col="lightgrey",add=TRUE)
title("End of Day")
```

```{r}
plot(1,1,xlim=c(0,4),ylim=c(0,65),type="n",
     xlab="",ylab="Prevalence (%)",axes=FALSE)
## bottom axis, with user-specified labels
axis(side=1,at=1:3,labels=c("Zone 1","Zone 2","Zone 3"))
axis(side=2)
vioplot(Final$w.z1.post,at=1,col="lightgrey",add=TRUE)
vioplot(Final$w.z2.post,at=2,col="lightgrey",add=TRUE)
vioplot(Final$w.z3.post,at=3,col="lightgrey",add=TRUE)
title("End of Day")
```

```{r}
plot(1,1,xlim=c(0,4),ylim=c(0,65),type="n",
     xlab="",ylab="Prevalence (%)",axes=FALSE)
## bottom axis, with user-specified labels
axis(side=1,at=1:3,labels=c("Zone 1","Zone 2","Zone 3"))
axis(side=2)
vioplot(Final$w.z1.beg,at=1,col="lightgrey",add=TRUE)
vioplot(Final$w.z2.beg,at=2,col="lightgrey",add=TRUE)
vioplot(Final$w.z3.beg,at=3,col="lightgrey",add=TRUE)
title("Beginning of Day")
```





